name: workspace
description: Step by step to safety.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 
    sdk: flutter         # 
  adobe_xd: ^1.1.0+1
  form_field_validator: ^1.0.1
  http: ^0.13.1
  flutter_svprogresshud: ^0.0.6
  fluttertoast: ^7.1.6
  shared_preferences: ^0.5.12+4
  image_picker: ^0.7.4
  im_animations: ^0.1.1
  fading_images_slider: ^0.0.1+1
  clean_settings_nnbd: ^0.2.0
  ffi: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1
  pin_code_fields: ^7.0.0
  number_animation: ^0.1.2
  liquid_progress_indicator_ns: ^1.0.0
  flutter_typeahead: ^2.0.0
  google_maps_flutter: ^2.0.3
  geolocator: ^6.2.1
  geocoder: ^0.2.1
  delayed_display: ^2.0.0
  flutter_swiper: ^1.1.6
  super_tooltip: ^0.9.6
  bluetoothadapter: ^1.1.3
  flutter_bluetooth_serial: ^0.2.2
  flutter_sms: ^2.1.1
  smart_select: ^4.3.2
  sticky_headers: "^0.1.8"
  mailer: ^3.3.0
  syncfusion_flutter_charts: ^18.4.30
  sms: ^0.2.0
  flushbar: ^1.10.4
  #moez
  #flutter_phone_state: ^0.5.8
  jiffy: ^4.1.0
  flutter_phone_direct_caller: ^2.0.0
  avatar_glow: ^2.0.1
  flutter_local_notifications: ^1.4.4+2 
  pedometer: ^2.1.0
  date_format: ^2.0.2
  get_ip: ^0.4.0
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  step_counter: ^0.0.2
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/en/
    - assets/ar/
    - assets/fr/
    - assets/profil/
    - lib/AnalyseModule/assets/
    - lib/AnalyseModule/assets/smslogo.png
    - lib/AnalyseModule/assets/emaillogo.png
    - lib/Languages/Lang/en.json
    - lib/Languages/Lang/fr.json
    - lib/Languages/Lang/ar.json
  #  - lib/deviceModule/assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/Montserrat.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#ffffff"
  image: assets/fflogo.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  andoird: "assets/icon_android.png"
  image_path_ios: "assets/icon_ios.png"
  image_path_android: "assets/icon_android.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon_android.png"
  image_path: "assets/icon_android.png"
