version: '3.8'


services: 
    app_back:
      build: 
        context: ./app_back
        dockerfile: Dockerfile 
      restart: unless-stopped
      ports:
        - "54001:34000"
      depends_on:
        - database
    database:
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "54004:27017"
    